version: "3.9"

services:

  backend:
    image: irtaza0007/3tier-backend:latest
    container_name: backend

    environment:
      - MONGO_URI=mongodb://172.31.17.225:27017/mydb

    ports:
      - "5000:5000"

    restart: unless-stopped

  frontend:
    image: irtaza0007/3tier-frontend:latest
    container_name: frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped
